---
#! www.yml : playbook  for web servers
- hosts: www
  remote_user: root
  become: yes
  pre_tasks:
    - shell: echo 'I ":" Beginning to configure web server...'
  roles:
    - { role: nginx, port: 8080 }
  post_tasks:
    - shell: echo 'I ":" Done configuring nginx web server...'